networks:
  tests-net:
    name: tests-net

x-worker-defaults: &worker_defaults
  image: mysite:latest
  build:
    context: ..
    dockerfile: dockerfiles/site/Dockerfile.site
  depends_on:
    - selenium-hub
  restart: unless-stopped
  networks:
    - tests-net

x-testpython-defaults: &testpython_defaults
  image: testimagepython:latest
  build:
    context: ..
    dockerfile: dockerfiles/python/DockerfilePython.base
  mem_limit: 1g
  cpus: 1.0
  shm_size: 1g
  pids_limit: 300

x-testjava-defaults: &testjava_defaults
  image: testimagejava:latest
  build:
    context: ..
    dockerfile: dockerfiles/java/DockerfileJava.base
  mem_limit: 1g
  cpus: 1.0
  shm_size: 1g
  pids_limit: 300


services:
  redis:
    image: redis:7
    container_name: redis-local
    command: ["redis-server", "--requirepass", "test1234"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  selenium-hub:
    networks:
      - tests-net
    image: selenium/hub:4.11.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-node-chrome:
    networks:
      - tests-net
    image: selenium/node-chrome:4.11.0
    #container_name: selenium-node-chrome
    shm_size: 3gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=true 
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #  - SE_NODE_MAX_SESSIONS=5
    #  - SE_NODE_OVERRIDE_MAX_SESSIONS=true

volumes:
  kafka_data: