networks:
  tests-net:
    name: tests-net

services:
  redis:
    image: redis:7
    container_name: redis-local
    command: ["redis-server", "--requirepass", "test1234"]
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles: ["redis"]

  kafka:  
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    profiles: ["kafka"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,CONTROLLER://kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  selenium-hub:
    networks:
      - tests-net
    image: selenium/hub:4.11.0
    container_name: selenium-hub
    profiles: ["selenium"]
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-node-chrome:
    networks:
      - tests-net
    image: selenium/node-chrome:4.11.0
    profiles: ["selenium"]
    shm_size: 3gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=true 
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

volumes:
  kafka_data: